// src/components/ColorModeSwitcher.tsx
import { useState } from "react";

const MODE = {
    LIGHT: "light",
    DARK: "dark",
} as const;

export const ColorModeSwitcher = () => {
    const [mode, setMode] = useState("light");

    const setTheme = () => {
        const html = document.querySelector("html");

        switch (mode) {
            case MODE.LIGHT:
                setMode(MODE.DARK);
                break;
            case MODE.DARK:
                setMode(MODE.LIGHT);
                break;
        }

        html?.classList.toggle(MODE.DARK);
        html?.classList.toggle(MODE.LIGHT);
    };

    return (
        <button
            className="absolute top-8 right-[8%] lg:right-1/4"
            onClick={setTheme}
        >
            {mode === MODE.LIGHT ? (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    className="w-6 h-6 stroke-neutral-50"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                    />
                </svg>
            ) : (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1"
                    className="w-6 h-6 stroke-neutral-950"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z"
                    />
                </svg>
            )}
        </button>
    );
};

// components/ColorModeSwitcher.vue
<script setup lang="ts">
    import { useColorMode } from '@vueuse/core'

    enum ColorMode {
        Dark = 'dark',
        Light = 'light'
    }

    const mode = useColorMode()

    const ariaLabelText = computed(() => {
        return `Click here to change the theme to ${mode.value === ColorMode.Light ? 'dark' : 'light'} mode`
    
    })

    const setMode = () => {
        if (mode.value === ColorMode.Dark) {
            mode.value = ColorMode.Light
        } else {
            mode.value = ColorMode.Dark
        }
    }

    onMounted(() => {
        mode.value = ColorMode.Light
    })
</script>

<template>
    <button 
        class="absolute top-8 right-[8%] lg:right-1/4"
        type="button"
        :aria-label="ariaLabelText"
        @click="setMode"
    >
        <svg 
            v-if="mode === ColorMode.Light"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            class="w-6 h-6 stroke-neutral-50"
        >
            <path 
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
            />
        </svg>
        <svg 
            v-else
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            class="w-6 h-6 stroke-neutral-950"
        >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z"
            />
        </svg>

    </button>
</template>
